grp:
  game:
    n_players: 3
  data_glob: "data/mjsoul/mjsoul-3p/train/**/*.jsonl"
  val_data_glob: "data/mjsoul/mjsoul-3p/val/**/*.jsonl"
  output: artifacts/3p/grp_model.pth
  device: cuda
  batch_size: 1024
  num_workers: 20
  num_epochs: 1
  lr: 5e-4
  lr_eta_min: 1e-7
  samples_per_file: 30
  wandb_entity: jiucheng-z-university-of-waterloo
  wandb_project: riichippo
  wandb_tags: [grp]
