bc:
  game:
    n_players: 4
  online: true
  grp_model: artifacts/4p/grp_model.pth
  output: artifacts/4p/bc_model.pth
  device: cuda
  batch_size: 128
  lr: 5e-4
  lr_min: 1e-5
  gamma: 1.0
  pts_weight: [6.0, 4.0, 2.0, 0.0]
  weight_decay: 0.1
  value_coef: 0.5
  wandb_entity: jiucheng-z-university-of-waterloo
  wandb_project: riichippo
  wandb_tags: [online, bc_model]
  # Online teacher settings
  teacher_model_name: kanachan
  teacher_model_path: artifacts/teacher/best_model.pth
  num_ray_workers: 4
  num_envs_per_worker: 16
  num_steps: 500
  # Model (ActorCriticNetwork)
  model_class: riichienv_ml.models.actor_critic.ActorCriticNetwork
  encoder_class: riichienv_ml.features.feat_v1.ObservationEncoder
  evaluator:
    model_path: artifacts/teacher/best_model.pth
    eval_episodes: 48
    eval_interval: 50
    eval_device: cuda
  model:
    in_channels: 74
    num_blocks: 16
    conv_channels: 192
    fc_dim: 512
    num_actions: 82
    tile_dim: 34
