ppo:
  game:
    n_players: 4
  algorithm: ppo
  load_model: artifacts/4p/bc_model.pth
  device: cuda
  model_class: riichienv_ml.models.actor_critic.ActorCriticNetwork
  encoder_class: riichienv_ml.features.feat_v1.ObservationEncoder
  num_workers: 4
  num_steps: 500
  lr: 1e-5
  gamma: 1.0
  max_grad_norm: 0.5
  ppo_clip: 0.02
  ppo_epochs: 2
  gae_lambda: 0.95
  entropy_coef: 0.001
  value_coef: 0.5
  grp_model: artifacts/4p/grp_model.pth
  pts_weight: [6.0, 4.0, 2.0, 0.0]
  weight_decay: 0.1
  alpha_kl: 0.1
  alpha_kl_warmup_steps: 50
  aux_weight: 0.0
  eval_interval: 50
  eval_episodes: 192
  worker_device: cuda
  gpu_per_worker: 0.2
  num_envs_per_worker: 48
  checkpoint_dir: artifacts/4p/ppo/checkpoints
  wandb_entity: jiucheng-z-university-of-waterloo
  wandb_project: riichippo
  evaluator:
    model_path: artifacts/teacher/best_model.pth
    eval_episodes: 48
    eval_device: cuda
  wandb_tags: [online, ppo, v1]
  model:
    in_channels: 74
    num_blocks: 16
    conv_channels: 192
    fc_dim: 512
    num_actions: 82
    tile_dim: 34
    aux_dims: 4
