grp:
  game:
    n_players: 4
  data_glob: data/mjsoul/mjsoul-4p/train/**/*.jsonl.gz
  val_data_glob: data/mjsoul/mjsoul-4p/val/**/*.jsonl.gz
  output: artifacts/4p/grp_model.pth
  device: cuda
  batch_size: 512
  num_workers: 8
  num_epochs: 1
  lr: 5e-4
  lr_eta_min: 1e-7
  samples_per_file: 32
  wandb_entity: jiucheng-z-university-of-waterloo
  wandb_project: riichippo
  wandb_tags: [grp]
